#include <stdio.h>
#include <string_view>
#include <ctype.h>
#include <string.h>
#include <algorithm>
#define NOLOGS_H 1
#include "inout.hpp"
#include "destruct.hpp"
#define LOGGER(...) fprintf(stderr,__VA_ARGS__)
#include "strsepconcat.hpp"
/*
<script type="module" >
import { setlang } from "https://www.juggluco.nl/Jugglucohelp/code/settrans.js";
let translations=[
"be", "de", "es", "fr", "nl", "pl", "pt", "ru", "uk", "zh",
];
setlang(translations,"libreview.html");
</script> */
static void addcomments(FILE *fp,const char *inname) {
    fprintf(fp,R"(
<!--***********************************************************************************-->
<!--***********************************************************************************-->
<!--**** THIS FILE IS AUTOMATICALLY GENERATED FROM %s. DO NOT EDIT! *****-->
<!--***********************************************************************************-->
<!--***********************************************************************************-->
)",inname);
}
void langlist(FILE*fp,char **names,int len,const char *filename,const char *inname) {
  addcomments(fp,inname);
 fprintf(fp,R"(<script type="module" >
import { setlang } from "https://www.juggluco.nl/Jugglucohelp/code/settrans.js";
let translations=[)");
    for(int i=0;i<len;i++) { 
        fprintf(fp,R"("%.02s", )",names[i]);
        }
    fprintf(fp,R"(];
setlang(translations,"%s");
</script>)",filename);
      }
void mklinks(FILE *fp,char **names,int len,const char *filename,const char *inname) {
    fprintf(fp,R"(<p>)");
    for(int i=0;i<len;i++) { 
        fprintf(fp,R"(<a href="https://www.juggluco.nl/Jugglucohelp/%.02s/%s">%.02s</a>&emsp;&emsp;)",names[i],filename,names[i]);
        }
    fprintf(fp,R"(<a href="https://www.juggluco.nl/Jugglucohelp/%s?lang=en">en</a>&emsp;&emsp;</p>)",filename);
     }

template <class T, std::size_t N> std::pair<int,int> includingstring(const T (&findstr)[N], const char *input, int len) {
    auto comp=[](const char one,const char two)->bool {return tolower(one)==tolower(two);};
    const char *endinput=input+len;
    const char *found=std::search(input,endinput,findstr,findstr+N-1,comp);
    if(found==endinput)  {
        fprintf(stderr,"%s not found\n",findstr);
        return {-1,-1};
        }
    const char *start=std::find(found,endinput,'>');
    if(start==endinput) {
      fprintf(stderr,"> not found\n");
        return {-2,-2};
        }
    return {found-input,start-input+1};
    }
strsepconcat  getendname(std::string_view inname) {
    return {"",inname.substr(0,inname.size()-7),inname.substr(inname.size()-4)};
    }
int patchfile(const char *inname,const char *filename,char **names,int nr,bool addscript,bool giveindex) {
    Readall file(inname);
    if(!file.data()) {
        perror(inname);
        return -1;
        }
    char *input=file.data();
    auto newname=getendname(inname);
    FILE *outfile=fopen(newname.data(),"w");
    if(!outfile) {
        perror(newname.data());
        return -2;
        }
    destruct _([outfile]{fclose(outfile);});
    int htmlpos;
    if(addscript) {
        const auto [_,htmlpos]=includingstring(R"(<html)",input,file.size());
        if(fwrite(input,htmlpos,1,outfile)!=1) {
            perror("fwrite 2");
            return -4;
            }
        langlist(outfile,names,nr,filename,inname);
        }
    else {
        htmlpos=0;
        }
    auto [startbody,bodypos]=includingstring(R"(<body)",input+htmlpos,file.size()-htmlpos);
    if(bodypos<0) {
        return -3;
        }
    if(fwrite(input+htmlpos,startbody,1,outfile)!=1) {
        perror("fwrite 3");
        return -5;
        }
    auto useinname=!addscript?inname:nullptr;
      if(useinname)
            addcomments(outfile,inname);
    if(fwrite(input+htmlpos+startbody,bodypos-startbody,1,outfile)!=1) {
        perror("fwrite 3");
        return -5;
        }
    if(giveindex) {
        if(addscript)
           fprintf(outfile,R"(<p><a href="https://www.juggluco.nl/Jugglucohelp/index.html">index</a></p>)");
        else
           fprintf(outfile,R"(<p><a href="https://www.juggluco.nl/Jugglucohelp/%.02s/index.html">index</a></p>)",inname);
        }
    mklinks(outfile,names,nr,filename,useinname);
    int endlen=file.size()-bodypos-htmlpos;
    if(fwrite(input+bodypos+htmlpos,endlen,1,outfile)!=1) {
        perror("fwrite 4");
        return -6;
        }
     return 0;
    }
int main(int argc,char **argv) {
    bool giveindex;
    int startindex;
    if(argc>1&&strcmp(argv[0],"-noi")) {
        giveindex=false;
        startindex=2;
        }
    else {
        giveindex=true;
        startindex=1;
        }
    char **names=argv+startindex;
    int nr=argc-startindex;
    if(nr) {
        auto newname=getendname(names[0]+3);
        const char *filename=newname.data();
        for(int i=0;i<nr;++i) {
            const char *fullname=names[i];
            patchfile(fullname,filename,names,nr,false,giveindex);
            }

        patchfile(names[0]+3,filename,names,nr,true,giveindex);
        }
    }
